// Gemini multimodal reconstruction for DOCX content that the heuristic can't
// handle — typically Word documents that were generated by converting a
// math-heavy PDF, where every symbol got flattened (e.g. "x²" → "x2",
// fractions split across cells "2 3 sq unit", question numbers stripped),
// AND where any equation that was originally typeset got dumped into the
// DOCX as a raster image with OCR garbage next to it.
//
// We send paragraphs + referenced images to Gemini Flash in ONE multimodal
// call so it can read the math directly from each image and ignore the
// surrounding OCR debris. The output mirrors the heuristic parser's
// discriminated-union ParsedQuestion shape, so the rest of the import
// route stays untouched.

import { geminiGenerateText, GeminiError, type GeminiInlineImage } from './gemini'
import { lenientJsonParse } from './json-utils'
import { z } from 'zod'
import type { ParsedQuestion } from '@/lib/integrations/document/parse-questions-text'
import type { DocxImage } from '@/lib/integrations/document/extract-docx'

const geminiQuestionSchema = z.object({
  question_no: z.number().int().nullable().optional(),
  question_type: z.enum(['mcq', 'subjective', 'numerical']),
  question_body: z.string().min(1),
  options: z.array(z.string()).default([]),
  marks: z.number().nullable().optional(),
})

const geminiResponseSchema = z.object({
  questions: z.array(geminiQuestionSchema).default([]),
})

const PROMPT_HEADER = `You are reconstructing exam questions from a Microsoft Word (.docx) file.
The source was almost certainly produced by converting a PDF, so:

  - Plain-text math is flattened: "x²" → "x2", "2/3" → "2 3", "d²y/dx²"
    → "d2y dx2", "√3" loses the radical, etc.
  - ANY equation that was originally typeset got dumped into the DOCX as a
    rasterised IMAGE, with the converter's OCR debris pasted next to it as
    garbage text (long random digit strings like "1301496386246",
    repeated single letters like "x x", numeric fragments that don't
    parse as a question).
  - Question numbering is often missing, split across paragraphs, or
    broken into single-character cells.

You will receive TWO kinds of input below:

  1) The full paragraph text of the DOCX, with [[IMG:filename]] markers
     inserted where embedded images appear.
  2) The actual bytes of each referenced image, attached inline in the
     same order they appear in the text. The Nth attached image
     corresponds to the Nth distinct [[IMG:filename]] marker, listed
     under "Image references" below.

Use the attached image content as the SOURCE OF TRUTH for any equation
that appears as an image. Treat OCR debris (long random digit strings,
repeated lone letters, garbled fragments) immediately adjacent to a
[[IMG:...]] marker as NOISE — drop it from question_body. The actual
mathematical content is what you see in the image.

Output ONE JSON object with this exact shape:

{
  "questions": [
    {
      "question_no": <integer or null>,
      "question_type": "mcq" | "numerical" | "subjective",
      "question_body": "<full question text, math in LaTeX>",
      "options": ["<A>", "<B>", "<C>", "<D>"],
      "marks": <number or null>
    }
  ]
}

Rules:
- Convert ALL math notation to proper LaTeX. Wrap inline math in \\( ... \\)
  and display math in \\[ ... \\]. Examples:
    "x2 = y"             → "\\(x^2 = y\\)"
    "2 3 sq unit"        → "\\(\\tfrac{2}{3}\\) sq unit"
    "d2y dx2"            → "\\(\\dfrac{d^{2}y}{dx^{2}}\\)"
    "sqrt 3 by 2"        → "\\(\\tfrac{\\sqrt{3}}{2}\\)"
    "[[IMG:integral.png]]" (image shows ∫ 3cos√x/√x dx)
                         → "\\(\\int \\frac{3 \\cos \\sqrt{x}}{\\sqrt{x}}\\, dx\\)"
- MCQ detection — set question_type="mcq" and emit exactly 4 options in
  A/B/C/D order whenever ANY of these patterns appears for a question:
    a) the literal (A)(B)(C)(D) prefix on each option, or
    b) FOUR short parallel paragraphs immediately after the question
       body that look like answer choices (e.g. "1 sq unit", "2 sq units",
       "3 sq units", "4 sq units" — assign them to A,B,C,D in order), or
    c) four options where the markers were stripped to bare numbers
       ("1." "2." "3." "4.") or letters split across cells.
  If you cannot recover exactly 4 options, fall back to subjective.
- Otherwise pick "numerical" (answer is a single numeric value) or
  "subjective" (descriptive). NEVER guess or include a correct answer
  — the schema has no correct_option field.
- IMAGE PLACEHOLDERS in your OUTPUT: only KEEP an [[IMG:filename]] marker
  in question_body if the image is a non-mathematical DIAGRAM (a figure
  the student must look at — geometry, graph, circuit, table). If the
  image is an EQUATION or formula, replace the marker with the LaTeX
  you read from the image and DROP the marker.
- SKIP non-question content: page headers/footers, page numbers
  ("Page 7 of 23"), paper codes ("65/S/1"), watermarks, blank instruction
  paragraphs, section labels alone.
- question_no: integer if recoverable, else null.
- marks: integer from a "[2]"-style marker if present, else null.
- If there are zero answerable questions, return {"questions": []}.
- ALL backslashes in LaTeX MUST be doubled in the JSON output. Write
  \\(, \\frac, \\sqrt — never \(, \\frac, \\sqrt. Single backslashes are
  invalid JSON escapes and your response will be rejected.
- Output ONLY the JSON object. No markdown fences, no commentary.
`

const PROMPT_PARAGRAPHS_HEADER = `\nParagraphs (one per line):\n---\n`
const PROMPT_PARAGRAPHS_FOOTER = `\n---\n`

export interface ParseFromDocxTextResult {
  parsed: ParsedQuestion[]
  usage: { totalTokens: number }
  imagesAttached: number
}

const GEMINI_MIMES: ReadonlySet<string> = new Set([
  'image/png',
  'image/jpeg',
  'image/webp',
])

// Cap attached images per call so a docx with dozens of decorative logos
// doesn't blow past Gemini's per-request size limit. Each attached image
// costs ~258+ tokens at base resolution; 12 keeps us well under Flash's
// 1M-token window even on a busy paper.
const MAX_ATTACHED_IMAGES = 12

// Skip tiny images (< 1 KB) — they're almost always decorative dingbats,
// not equations. Cuts noise and tokens.
const MIN_IMAGE_BYTES = 1024

export async function parseQuestionsFromDocxText(
  paragraphs: string[],
  images: DocxImage[] = [],
): Promise<ParseFromDocxTextResult> {
  const text = paragraphs.map((p) => p.trim()).filter((p) => p.length > 0).join('\n')
  if (text.length === 0) {
    return { parsed: [], usage: { totalTokens: 0 }, imagesAttached: 0 }
  }

  const MAX_INPUT_CHARS = 200_000
  const inputText = text.length > MAX_INPUT_CHARS ? text.slice(0, MAX_INPUT_CHARS) : text

  // Find which images are actually referenced via [[IMG:filename]] markers
  // in the paragraph text — decorative images that nothing references
  // aren't worth Gemini's token spend.
  const referenced = new Set<string>()
  const placeholderRe = /\[\[IMG:([^\]]+)\]\]/g
  let m: RegExpExecArray | null
  while ((m = placeholderRe.exec(inputText))) referenced.add(m[1])

  const attachable: DocxImage[] = []
  for (const img of images) {
    if (!referenced.has(img.filename)) continue
    if (!GEMINI_MIMES.has(img.contentType)) continue
    if (img.data.length < MIN_IMAGE_BYTES) continue
    attachable.push(img)
    if (attachable.length >= MAX_ATTACHED_IMAGES) break
  }

  const inlineImages: GeminiInlineImage[] = attachable.map((img) => ({
    mimeType: img.contentType as GeminiInlineImage['mimeType'],
    data: img.data.toString('base64'),
  }))

  // Tell the model which file each attached image is, so the [[IMG:foo]]
  // markers in the text map cleanly to attachments.
  const refsBlock =
    attachable.length === 0
      ? '(no images attached)'
      : attachable
          .map((img, i) => `  ${i + 1}. attachment #${i + 1} = [[IMG:${img.filename}]]`)
          .join('\n')

  const prompt =
    PROMPT_HEADER +
    `\nImage references:\n${refsBlock}\n` +
    PROMPT_PARAGRAPHS_HEADER +
    inputText +
    PROMPT_PARAGRAPHS_FOOTER

  const result = await geminiGenerateText(
    prompt,
    inlineImages,
    { responseMimeType: 'application/json' },
  )

  let raw: unknown
  try {
    raw = lenientJsonParse(result.text)
  } catch {
    throw new GeminiError(
      'BAD_RESPONSE',
      `JSON.parse failed even after backslash-repair: ${result.text.slice(0, 500)}`,
    )
  }

  const parseResult = geminiResponseSchema.safeParse(raw)
  if (!parseResult.success) {
    throw new GeminiError(
      'BAD_RESPONSE',
      `Gemini JSON failed schema validation: ${parseResult.error.message}. Raw: ${result.text.slice(0, 500)}`,
    )
  }

  // Adapt Gemini's flat options[] shape to the heuristic's discriminated-
  // union ParsedQuestion (option_a..d for MCQ, no options field for
  // subjective). The route's `buildCandidate` switches on `kind`, so we
  // must produce the same kind shape it does.
  const adapted: ParsedQuestion[] = []
  for (const q of parseResult.data.questions) {
    if (q.question_type === 'mcq') {
      if (q.options.length !== 4) {
        // Drop malformed MCQs rather than misalign A/B/C/D. The route
        // wouldn't validate them anyway.
        continue
      }
      adapted.push({
        kind: 'mcq',
        question_no: q.question_no ?? null,
        section_label: null,
        question_body: q.question_body,
        option_a: q.options[0],
        option_b: q.options[1],
        option_c: q.options[2],
        option_d: q.options[3],
        marks: q.marks ?? null,
      })
    } else {
      // numerical from Gemini collapses to subjective in the DB — same
      // treatment the PDF Vision path uses. The user marks the correct
      // numerical answer manually in the question bank.
      adapted.push({
        kind: 'subjective',
        question_no: q.question_no ?? null,
        section_label: null,
        question_body:
          q.question_type === 'numerical'
            ? `[numerical — set answer in question bank] ${q.question_body}`
            : q.question_body,
        marks: q.marks ?? null,
      })
    }
  }

  return {
    parsed: adapted,
    usage: { totalTokens: result.usage.totalTokens },
    imagesAttached: inlineImages.length,
  }
}
